(function () {
  "use strict";

  function randomHex(len) {
    var bytes = new Uint8Array(len / 2);
    crypto.getRandomValues(bytes);
    var out = "";
    for (var i = 0; i < bytes.length; i++) {
      out += bytes[i].toString(16).padStart(2, "0");
    }
    return out;
  }

  // Base defaults. The random deviceId/groupId are generated by the service
  // worker on install; these are only a fallback if they do not exist yet.
  var DEFAULTS = {
    enabled: true,
    targetLabel: "",
    fakeLabel: "Integrated Webcam (1bcf:2b95)",
    fakeDeviceId: randomHex(64),
    fakeGroupId: randomHex(64)
  };

  var fields = {
    enabled: document.getElementById("enabled"),
    cameraSelect: document.getElementById("cameraSelect"),
    fakeLabel: document.getElementById("fakeLabel"),
    fakeDeviceId: document.getElementById("fakeDeviceId"),
    fakeGroupId: document.getElementById("fakeGroupId")
  };

  var detectBtn = document.getElementById("detect");
  var statusEl = document.getElementById("status");

  function showStatus(msg, isError) {
    statusEl.textContent = msg;
    statusEl.style.color = isError ? "#e06c75" : "#6cc070";
    setTimeout(function () {
      statusEl.textContent = "";
    }, 2400);
  }

  // Reads from storage the camera names collected by the content script and by
  // the detection page (the popup cannot show the permission dialog).
  function getStoredCameras() {
    return new Promise(function (resolve) {
      chrome.storage.local.get({ __availableCameras: [] }, function (s) {
        resolve((s && s.__availableCameras) || []);
      });
    });
  }

  // Fills the dropdown with the known webcams. Keeps the "Auto" option and
  // preserves the saved selection even if it has not been detected yet.
  function populateCameras(selectedLabel) {
    return getStoredCameras().then(function (stored) {
      // The popup also tries to enumerate in case the extension already has
      // permission.
      var extra =
        navigator.mediaDevices && navigator.mediaDevices.enumerateDevices
          ? navigator.mediaDevices.enumerateDevices().catch(function () {
              return [];
            })
          : Promise.resolve([]);

      return extra.then(function (devices) {
        var labels = {};
        stored.forEach(function (l) {
          if (l) labels[l] = true;
        });
        devices.forEach(function (d) {
          if (d.kind === "videoinput" && d.label) labels[d.label] = true;
        });

        var sel = fields.cameraSelect;
        sel.innerHTML = "";

        var auto = document.createElement("option");
        auto.value = "";
        auto.textContent = "Auto (detect virtual cameras)";
        sel.appendChild(auto);

        Object.keys(labels).forEach(function (label) {
          var opt = document.createElement("option");
          opt.value = label;
          opt.textContent = label;
          sel.appendChild(opt);
        });

        if (selectedLabel && !labels[selectedLabel]) {
          var saved = document.createElement("option");
          saved.value = selectedLabel;
          saved.textContent = selectedLabel + " (saved)";
          sel.appendChild(saved);
        }

        sel.value = selectedLabel || "";

        var count = Object.keys(labels).length;
        detectBtn.textContent = count
          ? "Detect more cameras"
          : "Detect cameras (grant permission)";
      });
    });
  }

  function applyToForm(cfg) {
    fields.enabled.checked = !!cfg.enabled;
    fields.fakeLabel.value = cfg.fakeLabel || "";
    fields.fakeDeviceId.value = cfg.fakeDeviceId || "";
    fields.fakeGroupId.value = cfg.fakeGroupId || "";
    populateCameras(cfg.targetLabel || "");
  }

  function readForm() {
    return {
      enabled: fields.enabled.checked,
      targetLabel: fields.cameraSelect.value || "",
      fakeLabel: fields.fakeLabel.value.trim() || DEFAULTS.fakeLabel,
      fakeDeviceId: fields.fakeDeviceId.value.trim() || DEFAULTS.fakeDeviceId,
      fakeGroupId: fields.fakeGroupId.value.trim() || DEFAULTS.fakeGroupId
    };
  }

  chrome.storage.local.get(DEFAULTS, function (stored) {
    applyToForm(Object.assign({}, DEFAULTS, stored || {}));
  });

  // The toolbar popup cannot show the camera permission dialog, so we open an
  // extension tab where the dialog does appear.
  detectBtn.addEventListener("click", function () {
    var url = chrome.runtime.getURL("request.html");
    if (chrome.tabs && chrome.tabs.create) {
      chrome.tabs.create({ url: url });
    } else {
      window.open(url, "_blank");
    }
    showStatus("Grant permission in the opened tab, then come back here.");
  });

  // Refresh the dropdown live when new cameras are detected.
  chrome.storage.onChanged.addListener(function (changes, area) {
    if (area === "local" && changes.__availableCameras) {
      populateCameras(fields.cameraSelect.value);
    }
  });

  fields.enabled.addEventListener("change", function () {
    chrome.storage.local.set({ enabled: fields.enabled.checked });
  });

  document.getElementById("save").addEventListener("click", function () {
    chrome.storage.local.set(readForm(), function () {
      showStatus("Saved. Reload the page to apply.");
    });
  });

  document.getElementById("reset").addEventListener("click", function () {
    // Ask the service worker for a random webcam name from the usb.ids list;
    // fall back to the default on any failure.
    chrome.runtime.sendMessage({ type: "randomizeName" }, function (resp) {
      var name =
        (!chrome.runtime.lastError && resp && resp.name) || DEFAULTS.fakeLabel;
      var fresh = Object.assign({}, DEFAULTS, {
        fakeLabel: name,
        fakeDeviceId: randomHex(64),
        fakeGroupId: randomHex(64)
      });
      chrome.storage.local.set(fresh, function () {
        applyToForm(fresh);
        showStatus("Reset (new identity).");
      });
    });
  });
})();
